Better file path handling
stsquad/dired-rsync pull request #35
Opened 2022-06-06 19:22 UTC by rayes0

Fixes some things with file path handling.

1. File paths with spaces or other special characters will already be escaped by `shell-quote-argument`, and enclosing in double quotes messes it up. This has been previously mentioned in #34.
2. Because we are no longer double quoting, filenames with dashes will be interpreted as arguments by some shells. So we add `--` as the last option in `dired-rsync-options` to prevent this.

_n.b._ - Unrelated to this PR, I'd suggest changing dired-rsync to use `make-process` (see https://www.gnu.org/software/emacs/manual/html_node/elisp/Asynchronous-Processes.html) to run rsync directly without dependence on the current shell. I see lots of people reporting shell-related things in the issues section, most of which can likely be mitigated by switching to `make-process`, which should work in a consistent way across all systems emacs supports.

2022-06-18 05:22 UTC, PRESFIL commented
Review please. :pray:

2022-07-12 18:50 UTC, PRESFIL commented
Any updates?

2022-07-13 09:57 UTC, stsquad requested changes
Please open code the -- rather than extend dired-rsync-options

2022-07-22 10:32 UTC, stsquad commented
Hmm $USER will be the local env setting which I don't think works because that might not match the user of the final destination - this is why we extract the user field from the tramp URLs.

2022-07-23 11:10 UTC, PRESFIL commented
OK, now I seem to understand what the problem is, but this is a
topic for a separate conversation :smiley:. I specified users for `from`
and `to` via `@` and it did the trick.

You were right about the necessary edits.

My working setup is as follows:

```diff
diff --git a/dired-rsync.el b/dired-rsync.el
index 4c62de2..e005c52 100644
--- a/dired-rsync.el
+++ b/dired-rsync.el
@@ -53,7 +53,7 @@
   :type 'string
   :group 'dired-rsync)

-(defcustom dired-rsync-options "-az --info=progress2 --"
+(defcustom dired-rsync-options "-az --info=progress2"
   "The default options for the rsync command."
   :type 'string
   :group 'dired-rsync)
@@ -311,7 +311,7 @@ there."
                                   (dired-rsync--get-remote-port) dhost)
                      shost
                      (format
-                      "\"%s %s -e \\\"%s\\\" %s %s@localhost:%s\""
+                      "\"%s %s -e \\\"%s\\\" -- %s %s@localhost:%s\""
                       dired-rsync-command
                       dired-rsync-options
                       (dired-rsync--get-remote-portfwd)
```

@rayes0 , can you apply this patch?

p.s. Maybe he made it possible to write in the branch.

2022-07-29 10:35 UTC, stsquad commented
Ok I've manually merged this while tweaking the commit and incorporating @PRESFIL's suggestion.

2022-07-29 10:35 UTC, closed without merging